// Generated by CoffeeScript 1.3.3
(function() {
  var ContactForm,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  ContactForm = (function(_super) {

    __extends(ContactForm, _super);

    function ContactForm() {
      return ContactForm.__super__.constructor.apply(this, arguments);
    }

    ContactForm.prototype.template = function(built) {
      return built("<form>\n  <textarea></textarea>\n  <button>Send</button>\n</form>");
    };

    ContactForm.prototype.elements = function(add) {
      add('msg', 'textarea');
      return add('btn', 'button');
    };

    ContactForm.prototype.events = function(add) {
      return add('submit', function(el, e) {
        e.preventDefault();
        return this.send_response();
      });
    };

    ContactForm.prototype.send_response = function() {
      var _this = this;
      this.btn.text('Sending...');
      return $.post('index.html', {
        msg: this.msg
      }, function() {
        _this.msg.val('');
        return _this.btn.text('Send');
      });
    };

    return ContactForm;

  })(Uniform);

  jQuery(function() {
    var form;
    form = new ContactForm;
    return $('body').append(form.el);
  });

}).call(this);
