// Generated by CoffeeScript 1.3.3
(function() {
  var ContactForm,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  ContactForm = (function(_super) {

    __extends(ContactForm, _super);

    function ContactForm() {
      return ContactForm.__super__.constructor.apply(this, arguments);
    }

    ContactForm.prototype.init = function() {
      ContactForm.__super__.init.apply(this, arguments);
      return $('body').append(this.el);
    };

    ContactForm.prototype.template = function(build) {
      return build("<form>\n  <textarea></textarea>\n  <button>Send</button>\n</form>");
    };

    ContactForm.prototype.elements = function() {
      return {
        msg: 'textarea',
        btn: 'button'
      };
    };

    ContactForm.prototype.events = function() {
      return {
        '': {
          'submit': function(el, e) {
            e.preventDefault();
            return this.sendResponse();
          }
        }
      };
    };

    ContactForm.prototype.sendResponse = function() {
      var _this = this;
      this.btn.text('Sending...');
      return $.post('index.html', {
        msg: this.msg
      }, function() {
        _this.msg.val('');
        return _this.btn.text('Send');
      });
    };

    return ContactForm;

  })(Uniform);

  jQuery(function() {
    return new ContactForm;
  });

}).call(this);
