// Generated by CoffeeScript 1.3.3
(function() {
  var App, Asset,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  App = (function(_super) {

    __extends(App, _super);

    function App() {
      return App.__super__.constructor.apply(this, arguments);
    }

    App.prototype.el = $('#unickr');

    App.prototype.elements = function() {
      return {
        url: '#url',
        gallery: '#gallery'
      };
    };

    App.prototype.events = function() {
      return {
        form: {
          submit: function(el, e) {
            var $gallery;
            e.preventDefault();
            $gallery = this.gallery;
            return this.nickUrl(this.url.val(), function() {
              return this.el.appendTo($gallery);
            });
          }
        }
      };
    };

    App.prototype.nickUrl = function(url, callback) {
      if (this.hasNicked == null) {
        this.gallery.html('');
        this.hasNicked = true;
      }
      return new Asset(url, callback);
    };

    return App;

  })(Uniform);

  Asset = (function(_super) {

    __extends(Asset, _super);

    function Asset(url, template_built) {
      this.url = url;
      this.template_built = template_built;
      Asset.__super__.constructor.call(this);
    }

    Asset.prototype.template = function(built) {
      return built("<div class=\"asset\">\n  <img src=\"" + this.url + "\" />\n</div>");
    };

    Asset.prototype.init = function() {
      Asset.__super__.init.apply(this, arguments);
      if (this.template_built != null) {
        return this.template_built();
      }
    };

    return Asset;

  })(Uniform);

  jQuery(function() {
    return new App;
  });

}).call(this);
