// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  this.EventMock = (function(_super) {

    __extends(_Class, _super);

    function _Class() {
      return _Class.__super__.constructor.apply(this, arguments);
    }

    _Class.prototype.events = function() {
      return {
        '': {
          an_event: function(el, e) {
            return this.events_triggered.push('an_event');
          }
        }
      };
    };

    _Class.prototype.init = function() {
      _Class.__super__.init.apply(this, arguments);
      return this.events_triggered = [];
    };

    return _Class;

  })(Uniform);

}).call(this);
